### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/tephinet#102]
### Done criteria
- [x] ~Map not aligning correctly (all the way to the right)~
- [x] ~Need colours on stat text and numbers to change on hover to #62c9d7~
- [x] ~Border around event type on event card and thinner text and not lowercase~
- [x] ~Flickr logo should be same colour for both dots~
- [x] ~Training programs - Too much space between intro text and map~
- [x] ~Training programs - Increase link target area for multiple programs~
- [x] ~Training programs - Tag text colour should be #091829~
- [x] Content page - Social media icons should be centred to 'Share' title
- [x] ~Search on header - Active state is too tall~

**Comment by cat-manta** [comment]
Screenshot of map issue
![screen shot 2018-07-24 at 16 13 33](https://user-images.githubusercontent.com/29398815/43150926-0e4d1eae-8f63-11e8-805a-7516695c265a.png)

**Comment by angievanhegan** [comment]
@dilwarhussain I added another task on here to delete all the content. This can be done when the design review stuff is all done.

**Comment by dilwarhussain** [comment]
Hey @cat-manta Could you review the changes please? Speak with @cutlern about the share icons.
