### ISSUE TITLE
Remove the summary field (in the card content)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/tephinet#112]
It currently appears on:

## Cards on the training programme landing page
![screen shot 2018-08-07 at 11 07 23](https://user-images.githubusercontent.com/3796718/43788862-2db7902c-9a34-11e8-99b3-1069054450d6.png)

## Training programme node page
![screen shot 2018-08-07 at 11 23 07](https://user-images.githubusercontent.com/3796718/43788954-5c57c370-9a34-11e8-98b9-225605a319e0.png)

**Comment by dilwarhussain** [comment]
@TinaRezvani 
Summary field has been removed from the card content.
The "Summary" on the node page is actually using the 'Description' field, which is a bit confusing, see below.

<img width="1362" alt="screen shot 2018-08-16 at 09 20 17" src="https://user-images.githubusercontent.com/29142647/44197116-b1047c80-a135-11e8-8228-cb2c69114136.png">

Would you like to remove this field also? You can also just leave this field empty if you don't want this to show on the node page.

**Comment by TinaRezvani** [comment]
Thanks @dilwarhussain. I deleted the text and saved the page. The section disappeared, but there's some error text at the top of the page (see attached screenshot). Just want to make sure everything's ok.
![page](https://user-images.githubusercontent.com/38916083/44210607-efe60280-a134-11e8-82ee-3b1ddaf699a6.jpg)
