### ISSUE TITLE
Full width image nugget (hero)

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#25]
### Done criteria
- [x] Import from alnap/ea-health
- [ ] Styling

---
### Links
- [Design - Landing page](https://invis.io/FUHS3VFM4TY) 
- [Design - Standard page with image](https://invis.io/BNHS3XZTQUZ)
- [Design - Standard page no image](https://invis.io/JHHS3ZPZBW5)

**Comment by angievanhegan** [comment]
Just putting this here in case this is what I'm supposed to be testing
http://tephinet-dev.mrmdev2.co.uk/angies-test-page

**Comment by angievanhegan** [comment]
@cat-manta This looks good to me. Do you want to check it? 

http://tephinet-dev.mrmdev2.co.uk/about/vision-mission-strategic-priorities
