### ISSUE TITLE
Attachment nugget

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#26]
### Done criteria
- [ ] TWEAK I can't upload an attachment in the sidebar, it requests a palette to be selected, but I don't have the option to choose one. 
- [x] Import/copy from BGS (talk to arseni if need to)
Change to existing attachment paragraph

- [x] Needs design for Attachments in main content/additional/postscript region
---
### Links
- [Design - Standard page with image](https://invis.io/BNHS3XZTQUZ)
- [Design - Standard page no image](https://invis.io/JHHS3ZPZBW5)

**Comment by angievanhegan** [comment]
@nadia847 Who needs to review this one?

**Comment by angievanhegan** [comment]
@nadia847 See tweak above

**Comment by angievanhegan** [comment]
@nadia847 I can upload an attachment in the sidebar now
