### ISSUE TITLE
Promo CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#27]
Note - the promos on the RT board are fine

### Done criteria
- [x] BLOCKED - need to confirm if we're using Parallax (YES WE ARE!)
- [x] Build using Parallax
- [x] @cat-manta to provide some more colours
- [x] Add custom fields
- [x] Theming

---
### Links
- [Promos](https://invis.io/XKFUOM14HA5#/295104792_Promos)
- [ Realtime board](https://realtimeboard.com/app/board/o9J_kziJ5ko=/?moveToWidget=3074457346085755156)

<img width="406" alt="screen shot 2018-05-10 at 10 09 42" src="https://user-images.githubusercontent.com/3796718/39877085-90a308e6-543a-11e8-9306-3e54c0c15914.png">

**Comment by angievanhegan** [comment]
@nadia847 I think this one is ready to go now.

**Comment by cat-manta** [comment]
@angievanhegan I've done two more promos:
https://invis.io/XKFUOM14HA5#/295104792_Promos

**Comment by angievanhegan** [comment]
@nadia847 How do I put a diferent colour on a promo please. They have four different ones to use.

**Comment by cat-manta** [comment]
@angievanhegan Yep that's fine!
