### ISSUE TITLE
Standard page CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#28]
### Done criteria
- [x] TWEAK Slideshow formatting is off
- [x] TWEAK Image not appearing in sidebar (content block)
- [ ] ~Import fonts~
- [ ] ~Heading styling~
- [ ] ~Links~
- [ ] ~Ordered lists~
 - [ ] ~Unordered lists~
- [ ] ~Sidebar nuggets~
- [ ] ~Block quotes~
- [ ] ~Image with caption (right, left centre)~
- [ ] ~FAQs (to use the text 'More' and 'Less'~
- [ ] ~Slideshows~

---
### Links
- [Design - Standard page with image](https://invis.io/BNHS3XZTQUZ)
- [Design - Standard page no image](https://invis.io/JHHS3ZPZBW5)

**Comment by angievanhegan** [comment]
@nadia847 Slideshow looks a bit funny. I may well have created it wrongly. 

<img width="407" alt="screen shot 2018-06-07 at 12 48 54" src="https://user-images.githubusercontent.com/3796718/41116884-2a6d9456-6a51-11e8-8122-fddd2ee346d4.png">

**Comment by angievanhegan** [comment]
@nadia847 The image isn't appearing in the sidebar: http://tephinet-dev.mrmdev2.co.uk/about/vision-mission-strategic-priorities

<img width="378" alt="screen shot 2018-06-07 at 14 16 49" src="https://user-images.githubusercontent.com/3796718/41121249-72d3b232-6a5d-11e8-930b-fcdedc34be88.png">

**Comment by angievanhegan** [comment]
@nadia847 

Sidebar > Feed > News latest isn't looking like the design.

DESIGN 

<img width="397" alt="screen shot 2018-06-07 at 14 43 12" src="https://user-images.githubusercontent.com/3796718/41122440-30eff34a-6a61-11e8-9a17-a23f564b7dcc.png">

DRUPAL

<img width="321" alt="screen shot 2018-06-07 at 14 44 02" src="https://user-images.githubusercontent.com/3796718/41122471-4074cca0-6a61-11e8-9d6c-31dc227b6ebe.png">

**Comment by nadia847** [comment]
@angievanhegan do we need to add a Google map embed? they don;t even have their address on their website

**Comment by angievanhegan** [comment]
@nadia847 I guess we could add one, they might want one one day
@ican-icant Do you want the address adding into the footer, or is it ok for it just to be on the contact us page?

**Comment by nadia847** [comment]
@angievanhegan I think the sidebar news image issue should be handled when we're editing news feeds which is not yet.

**Comment by angievanhegan** [comment]
@nadia847 yes. I created an issue for it.
