### ISSUE TITLE
Person CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#29]
### Done criteria
- [x] Node content
- [x] Card content
- [x] Style node
- [x] Style card 

---
### Links
- [Design - team page ](https://invis.io/UTHS4ADD8JV)
- [Design - person page ](https://invis.io/JWHS4BG9QZD)

**Comment by angievanhegan** [comment]
@cat-manta Do you want to check this? 

http://tephinet-dev.mrmdev2.co.uk/mr-steve-lacey
