### ISSUE TITLE
Team CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#30]
### Done criteria
- [x] Theming

---
### Links
- [Design - team page ](https://invis.io/UTHS4ADD8JV)
- [Design - person page ](https://invis.io/JWHS4BG9QZD)

**Comment by angievanhegan** [comment]
@cat-manta Looks good to me. Do you want to check it? 

http://tephinet-dev.mrmdev2.co.uk/about/our-team/womens-team
