### ISSUE TITLE
Footer CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#31]
### Done criteria
- [ ] ~Follow icons~
- [ ] Mailchimp embed
- [ ] Styling

---
### Links
- [Design - Landing page](https://invis.io/FUHS3VFM4TY)

**Comment by angievanhegan** [comment]
@nadia847 I've added the mailchimp account details

**Comment by cat-manta** [comment]
@cutlern Can you reduce the height of the footer please
