### ISSUE TITLE
Organisation CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#32]
### Done criteria
- [x] BLOCKER Need confirmation on requirements
- [ ] Card content
- [ ] Card theming

Node? Angie?!?!

---
### Links
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@nadia847 There's no requirement for a organisation page. Please can you update the content model and any related github issues? Does that mean we can close this issue? Thanks
