### ISSUE TITLE
Disable palettes

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#40]
### Done criteria
- [x] BLOCKER 'dependent on where we decide we need or don;t need palettes. eg need the field for promos but not elsewhere. also need to update content to ensure no region is using the wrong palette. has to be done before real content starts going in'
- [ ] Hide palette field after the bulk of theming is done

---
### Links
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@nadia847 Please can you add a note at the top to say why it's blocked? Thanks :o)

**Comment by nadia847** [comment]
@angievanhegan happy? :oP

**Comment by angievanhegan** [comment]
@nadia847 yes! Steve confirmed that we don't need palettes!
