### ISSUE TITLE
Hero nuggets

### ISSUE THREAD

**Issue by cutlern** [MantaRayMedia/tephinet#46]
### Done criteria
- [ ] ~Full-width-image~
- [ ] ~Content block~
- [ ] ~Title nugget~
- [ ] ~Title in hero or main content depending (main content by default)~
- [ ] ~Change hero nuggets to only allow one value~

---
### Links
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@nadia847 i'm not totally sure what to check here.
