### ISSUE TITLE
Follow & share icons

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#58]
### Done criteria
- [x] Add icon styles

Add more icons please:

LinkedIn: https://www.linkedin.com/in/tephinet-secretariat-7782336b/
YouTube: https://www.youtube.com/channel/UCKsLcv2C4luH6nfS_aq5tkg
Flickr: https://flickr.com/photos/tephinet/albums

**Comment by angievanhegan** [comment]
@nadia847 @cat-manta here's some more social media icons to add.

**Comment by nadia847** [comment]
@angievanhegan no work to be done here, other than decide if they want all the icons in the header. They just add the content, which i have now done.
