### ISSUE TITLE
Prep Drupal pages to look like the designs for demo (Fri 8 at 4pm)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/tephinet#63]
### Done criteria
- [ ] ~~[About page](http://tephinet-dev.mrmdev2.co.uk/about)~~
- [ ] ~~[Standard page - with hero](http://tephinet-dev.mrmdev2.co.uk/about/vision-mission-strategic-priorities)~~
- [ ] ~~[Standard page - without hero](http://tephinet-dev.mrmdev2.co.uk/about/our-history)~~
- [ ] ~~[Teams and people](http://tephinet-dev.mrmdev2.co.uk/about/our-team)~~
- [ ] ~~[Person page](http://tephinet-dev.mrmdev2.co.uk/mr-dave-melkman)~~
- [ ] ~~[Partners and donors](http://tephinet-dev.mrmdev2.co.uk/our-partners)~~

**Comment by angievanhegan** [comment]
@cat-manta @ican-icant These pages are ready for you to review.

**Comment by cat-manta** [comment]
@angievanhegan These all look fine to me, want to have a look @ican-icant ?
