### ISSUE TITLE
Training program CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#65]
### Done criteria
- [x] TWEAK Summary field should be large text
- [x] Build CT
- [x] Stats view display
- [x] Link view display
- [x] Program details view display
- [x] Areas of work display
- [x] Style node
- [x] Collapsible text sections for Program overview and Achievements
- [x] All node views should be set to display if published or admin and be hidden if empty
- [x] Add share links

---
### Links
- [Training programe design - node](https://invis.io/9HKN85MJFDA)
- [Drupal - node](http://tephinet-dev.mrmdev2.co.uk/training-programs/cameroon-fetp)
- [Training programe design - landing](https://invis.io/9UKN885BEC5)

**Comment by angievanhegan** [comment]
@dilwarhussain One small tweak

**Comment by dilwarhussain** [comment]
@angievanhegan Can make the text larger by using the 'Larger paragraph text' style from the Styles dropdown on the WYSIWYG. I think the setting may have been hidden from you but should be there now.
http://tephinet-dev.mrmdev2.co.uk/training-programs/cameroon-fetp
