### ISSUE TITLE
 Ensure Tephinet logo is correct

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/tephinet#68]
# We currently have this
![screen shot 2018-06-11 at 10 51 23](https://user-images.githubusercontent.com/3796718/41242534-6cadfe7a-6d65-11e8-8777-0ee944e1da38.png)

# But it should be this (as per the design)
![screen shot 2018-06-11 at 10 51 17](https://user-images.githubusercontent.com/3796718/41242535-6cdc98c0-6d65-11e8-9560-13c98f559e8e.png)

**Comment by angievanhegan** [comment]
@nadia847 This is the *only* thing that came out of the demo. It's ALL signed off so far

**Comment by nadia847** [comment]
Already fixed it, mate

On 11 Jun 2018, at 16:53, Angie Vanhegan <notifications@github.com<mailto:notifications@github.com>> wrote:


@nadia847<https://github.com/nadia847> This is the only thing that came out of the demo. It's ALL signed off so far
