### ISSUE TITLE
Check image sizes for team page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/tephinet#73]
### Done criteria
- [ ] ~1 in a row~
- [ ] ~2 in a row~
- [ ] ~3 in a row~
- [ ] ~4 in a row~
- [ ] ~6 in a row~

---
### Links
- [ ] [Drupal](http://tephinet-dev.mrmdev2.co.uk/about/our-team)
- [ ] [design](https://invis.io/K2KRFDUXPFR)

**Comment by angievanhegan** [comment]
@nadia847 It's adding grey lines on the triangle, on some but not all of them:

![screen shot 2018-06-18 at 11 28 20](https://user-images.githubusercontent.com/3796718/41549231-c74291f4-72ea-11e8-9128-5d5f386d8028.png)

**Comment by nadia847** [comment]
@angievanhegan ok now?

**Comment by angievanhegan** [comment]
@nadia847 Yup. I'm going to ask Steve to check these though.

**Comment by angievanhegan** [comment]
@ican-icant Can you check this please? Links to design and Drupal page at the top. Thanks
