### ISSUE TITLE
News CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#74]
### Done criteria
- [x] ~TWEAK Breadcrumb says 'News (menu position rule)'~
- [x] ~TWEAK Vertical spacing on Details (see screen grab below)~ [*Fixed in other branch]
- [x] ~TWEAK Hanging indents on bullets not working (in and out of FAQ)~
- [x] ~TWEAK Attachments in Main content not aligning in a grid~
- [x] ~Build node details views~
- [x] ~Check related content nugget is styled~
- [x] ~Ensure share icons display~
- [x] ~Style node~

---
### Links
- [Drupal test page](http://tephinet-dev.mrmdev2.co.uk/news-media/news/summary-of-the-10th-tephinet-regional-scientific-conference-of-the-americas)
- [Design](https://invis.io/DBM7C6M5EXT)

**Comment by nadia847** [comment]
@cutlern no type field

**Comment by angievanhegan** [comment]
![screen shot 2018-06-28 at 09 56 28](https://user-images.githubusercontent.com/3796718/42104533-8700d9e2-7b92-11e8-9852-d4cff102071f.png)

**Comment by angievanhegan** [comment]
@nadia847 Some little things. I just copied an existing news item - I thought that'd make a good test of what Tina needs. Thanks
