### ISSUE TITLE
Media CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#75]
### Done criteria
- [x] ~TWEAK Spacing should be even for text in sidebar nugget (see image below)~
- [ ] ~TWEAK No need to display the type on the sidebar nugget (or on the card content) CHECK WITH TINA~
- [x] ~TWEAK Change the name of the 'Annual report' type to 'Document or images'~
- [ ] ~Build Content type~
- [ ] ~Build node details view~
- [ ] ~Build media card/teaser~
- [ ] ~Add image style with video overlay~
- [ ] ~Ensure share icons appear~
- [ ] ~Style node~

---
### Links
- http://tephinet-dev.mrmdev2.co.uk/news-media/media/las-ma%C3%B1anitas
- [ ] ?

**Comment by nadia847** [comment]
@nadia847 media icon missing on dev site.

**Comment by angievanhegan** [comment]
![screen shot 2018-06-29 at 16 02 56](https://user-images.githubusercontent.com/3796718/42114808-093abfea-7bb6-11e8-94dd-ab28e4d9f234.png)

**Comment by angievanhegan** [comment]
@nadia847 Some teeny tweaks

**Comment by dilwarhussain** [comment]
@angievanhegan Ready for you to check http://tephinet-dev.mrmdev2.co.uk/news-media/media/las-ma%C3%B1anitas

**Comment by angievanhegan** [comment]
@dilwarhussain Are these heading fonts all the same size? Also, all the titles should be capitalised (Type is still lower case) Thanks

![screen shot 2018-07-04 at 08 12 42](https://user-images.githubusercontent.com/3796718/42279050-2204e8c0-7f62-11e8-9e35-0ee37adfcb75.png)

**Comment by dilwarhussain** [comment]
How about now @angievanhegan ? 
http://tephinet-dev.mrmdev2.co.uk/news-media/media/las-ma%C3%B1anitas
