### ISSUE TITLE
News & Media LP

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#76]
### Done criteria
- [ ] ~Featured nugget - Entity reference (limit 3) with option to switch large items left/right~
- [ ] ~Drop the toggle~
- [ ] ~Latest news display (left of media) with link to more news page~
- [ ] ~Latest media display (right of news) with link to more media page~
- [ ] ~No filters here~
- [ ] ~Styling~

---
### Links
- [Design in invision](https://invis.io/Z8M7UE2EQB5)
- [Drupal](http://tephinet-dev.mrmdev2.co.uk/news-media)

**Comment by angievanhegan** [comment]
@nadia847 This doesn't look like the design with a column for for News and one for Media. Also, it shouldn't have the search on it. And I can't work out how to add the three featured things at the top. 

(This one looks more like it should be the 'News' page that you see when you click on the 'See all news' button at the bottom of the News and Media LP)

**Comment by cutlern** [comment]
@angievanhegan There's a new feed for the News/media page called News and media latest which has the two column layout and links to the news and media pages (the site needed flushing so the option wasn't showing for you </3). The 3 featured cards can be added with the featured nugget :D
