### ISSUE TITLE
News LP

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#81]
### Done criteria
- [x] TWEAK - add pager at the bottom
- [ ] ~Featured (news) nugget?~
- [ ] ~No toggle~
- [ ] ~Text search (no other filters)~
- [ ] ~Pagers after 24? items~

---
### Links
- [Drupal](http://tephinet-dev.mrmdev2.co.uk/news-media/news-0)

**Comment by nadia847** [comment]
@ican-icant @angievanhegan 
Discuss with Tina - 
- What are the news types?
- Search text field vs filters
- Do we really need filtering by year?

**Comment by nadia847** [comment]
@angievanhegan this page is missing from the menu. needs to be investigated

**Comment by angievanhegan** [comment]
![screen shot 2018-06-28 at 09 56 28](https://user-images.githubusercontent.com/3796718/42042359-9d740e94-7ab9-11e8-8909-f05f08aa3a34.png)

**Comment by nadia847** [comment]
What’s wrong with t?

On 28 Jun 2018, at 15:57, Angie Vanhegan <notifications@github.com<mailto:notifications@github.com>> wrote:


[screen shot 2018-06-28 at 09 56 28]<https://user-images.githubusercontent.com/3796718/42042359-9d740e94-7ab9-11e8-8909-f05f08aa3a34.png>

**Comment by nadia847** [comment]
You're on the wrong card, @angievanhegan. This is for the Landing Page. Not the Content Type :grimacing:

**Comment by angievanhegan** [comment]
@nadia847 I've created this page, but I think it might need a bit more space around the top and it'll need the pager on the bottom.

**Comment by nadia847** [comment]
@angievanhegan not enough items to warrant the pager appearing yet.
