### ISSUE TITLE
Media LP

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/tephinet#82]
### Done criteria
- [ ] ~Featured (media) nugget?~
- [ ] ~No toggle~
- [ ] ~Text search (no other filters)~
- [ ] ~Pagers after 24? items~

---
### Links
- [Drupal](http://tephinet-dev.mrmdev2.co.uk/news-media/media)

**Comment by angievanhegan** [comment]
@nadia847 I don't think this needs the featured at the top. But it'll need a pager at the bottom.

**Comment by nadia847** [comment]
@angievanhegan the fratured can be added or removed by editing the page.

The pager will appear when there are more than 24 items and therefore something to actually page to

Pager is enabled in the view settings, I've just checked:

![screen shot 2018-07-02 at 10 40 57](https://user-images.githubusercontent.com/29143619/42156990-728c0226-7de4-11e8-803b-5b3e83df75ba.png)
