### ISSUE TITLE
Migrating all past events (67) to new site

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/tephinet#83]
See content under 'previous conferences' link on the left hand side of this page:
http://tephinet.org/conferences

1. Some events have images - can these be migrated
2. Can any attachments be migrated across? 
3. What can we do to minimise broken internal links?

**NOTE: Please can you track time to core site > conferences and events** This is in scope in the proposal 

### Links
- [Example ](http://tephinet.org/conference/2018-fetp-international-nights)

![screen shot 2018-07-25 at 08 25 53](https://user-images.githubusercontent.com/3796718/43203637-6979d70a-8fe4-11e8-8a57-eff01d04cbd4.png)

**Comment by angievanhegan** [comment]
Angie is confirming with Tina that she wants them all migrating as the earlier ones have very little content.

**Comment by angievanhegan** [comment]
Tina confirmed that she would like ALL past events.

**Comment by angievanhegan** [comment]
@russ-manta Please could you estimate this one? Thanks

**Comment by angievanhegan** [comment]
@meldera This is for you for next week. Thanks

**Comment by angievanhegan** [comment]
For w/c 30 July

**Comment by cat-manta** [comment]
@angievanhegan Didn't @ican-icant say I'm busy doing A&T next week?
