### ISSUE TITLE
Event CT

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/tephinet#89]
### Done criteria
- [x] TWEAK The headings should be on the white background
- [x] TWEAK It's not letting me add a country
- [x] TWEAK Date picker not working
- [x] Hide "Register" and "Submit abstract" buttons after end date of Event has passed.
- [x] Build RHS details views
- [x] Style node

## Links
- [Design] (https://invis.io/4KMLM4GR8W3)
- [Drupal page] (http://tephinet-dev.mrmdev2.co.uk/2018-tephinet-program-directors-meeting)

**Comment by angievanhegan** [comment]
@dilwarhussain 2 small tweaks.

**Comment by angievanhegan** [comment]
@dilwarhussain All working fine! Does this mean that someone has to create a page for every country? I'd assumed it was going to use the taxonomy, which already has all the countries in it. Would that not be easier for Tephinet?

**Comment by dilwarhussain** [comment]
@angievanhegan Would have to double check with @nadia847 But that's how this is working from what I can see. A node will be needed for any country being referenced. Same with Training programs and Projects.

**Comment by angievanhegan** [comment]
@dilwarhussain Sorry, just spotted a formatting tweak

**Comment by dilwarhussain** [comment]
@angievanhegan The main content is being created with nuggets so you can replicate the same heading style by adding a header in the WYSIWYG instead of using the title field. Sorry it is a little confusing because I hadn't explained how this is being created.

http://tephinet-dev.mrmdev2.co.uk/2018-tephinet-program-directors-meeting
