### ISSUE TITLE
Events LP

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/tephinet#93]
### Done criteria
- [x] ~Past events landing page~
- [x] ~Text search for past events only~
- [x] ~Ensure past and upcoming events buttons go to correct pages (done in content)~
- [x] ~Pager, 24 items~
- [x] ~Styling of cards (with and without image)~

## Links
- [Drual](http://tephinet-dev.mrmdev2.co.uk/events)
- [Design](https://invis.io/TVMOE9ON947)

**Comment by angievanhegan** [comment]
@dilwarhussain I was expecting the see the content in two columns, as per the design. Can I make it do that myself?

**Comment by dilwarhussain** [comment]
@angievanhegan Yes this can be selected in the feed settings in the nugget.

**Comment by angievanhegan** [comment]
@dilwarhussain Please can you show me how?

**Comment by angievanhegan** [comment]
Test comment please ignore or delete
