### ISSUE TITLE
Home page promo

### ISSUE THREAD

**Issue by cutlern** [MantaRayMedia/tephinet#94]
### Done criteria
- [x] Counters for case studies, projects and training programs
- [x] Field for long text

### TWEAKS
- [x] Manual counters with separate number, text and link field for each counter. Maximum 3 counters.
- [x] Image upload field for map in background.

---

### Links
- [ ] https://projects.invisionapp.com/d/main#/console/13375617/305882198/preview
- [ ] https://projects.invisionapp.com/d/main#/console/13375617/305882197/preview

**Comment by dilwarhussain** [comment]
@cutlern 

V2 has been chosen. With the text to the left. Map to the right.

The functionality has slightly changed on the way these boxes will be created.
No longer automatically calculated. Both the number and text will now be manual. So you can enter the number. You can enter the text. These are required fields. You can also add a link, this is optional.

Will also need an image field for the map in the background.

Have a look at the updated design to see examples of what they will be entering there: https://projects.invisionapp.com/d/main#/console/13375617/307099418/preview
